ci: assert if application started

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -138,3 +138,24 @@ jobs:
             
             # Start the new version of the application
             nohup /home/${{ secrets.SERVER_USERNAME }}/.asdf/installs/java/openjdk-21.0.2/bin/java -Dspring.profiles.active=${{ github.event.inputs.environment }} -jar /home/${{ secrets.SERVER_USERNAME }}/bots/bilubot-java/bilubot.jar > /home/${{ secrets.SERVER_USERNAME }}/bots/bilubot-java/bilubot.log 2>&1 &
+      - name: Check application startup
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USERNAME }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          script: |
+            # Wait for 1 minute for the application to start
+            for i in {1..60}; do
+              if grep -q "Started BilubotApplication" /home/${{ secrets.SERVER_USERNAME }}/bots/bilubot-java/bilubot.log; then
+                echo "Application started successfully"
+                exit 0
+              elif grep -q "Application run failed" /home/${{ secrets.SERVER_USERNAME }}/bots/bilubot-java/bilubot.log; then
+                echo "Application failed to start"
+                cat /home/${{ secrets.SERVER_USERNAME }}/bots/bilubot-java/bilubot.log
+                exit 1
+              fi
+              sleep 1
+            done
+            echo "Application did not start within 1 minute"
+            exit 1
